In [1]:
import pandas as pd 
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df_2 = pd.read_csv('companies.csv')

In [3]:
# Path_1 = "/content/Cresco Labs.csv"
# Path_2 = "/content/KFC Ltd (3420).csv"
# Path_3 = "/content/Белуга Групп ПАО (BELU).csv"
# a = pd.read_csv(Path_1)
# b = pd.read_csv(Path_2)
# c = pd.read_csv(Path_3)
# a_new = a[:200]['Цена'] 
# b_new = b[:200]['Цена'] 
# c_new = c[:200]['Цена'] 
# data_f = pd.DataFrame({'Cresco Labs' :a_new, 'KFC Ltd (3420)':b_new, 'Белуга Групп ПАО (BELU)':c_new})
# data_f.to_csv('companies.csv')
# new_df = pd.read_csv('companies.csv')
# df = pd.read_csv('companies.csv').drop('Unnamed: 0',axis = 1)
# s = []
# for el  in df['Cresco Labs']:
#   a,b = el.split(',')
#   s.append(int(a)+int(b)/(10**len(b)))
# s_2 = []
# [s_2.append(float(s_.split(',')[0])) for s_ in df['KFC Ltd (3420)']]
# df_2 = pd.DataFrame({'Cresco Labs' :s, 'KFC Ltd (3420)':s_2, 'Белуга Групп ПАО (BELU)':s_3})
           

In [4]:
# to download you have to apply file companies_f.csv to project
df_2 = pd.read_csv('/content/companies_f.csv')
# df_2 = pd.read_csv('/content/drive/MyDrive/companies_f.csv')
a = df_2['Cresco Labs']
b = df_2['KFC Ltd (3420)']
c = df_2['Белуга Групп ПАО (BELU)']

In [5]:
r_1 = a[:-1].div(a[1:].iloc[0]) -1
r_2 = b[:-1].div(b[1:].iloc[0]) -1
r_3 = c[:-1].div(c[1:].iloc[0]) -1

In [6]:
rm_1 = r_1.mean()
rm_2 = r_2.mean()
rm_3 = r_3.mean()
print("Expectation of:")
print(f"Cresco Labs = {rm_1}")
print(f"KFC Ltd (3420) = {rm_2}")
print(f"Белуга Групп ПАО (BELU) = {rm_3}")

Expectation of:
Cresco Labs = 0.3029299630402595
KFC Ltd (3420) = 0.12711903890312487
Белуга Групп ПАО (BELU) = -0.03462631240548707


In [7]:
var_1 = np.var(r_1)
var_2 = np.var(r_2)
var_3 = np.var(r_3)

print("Variance of:")
print(f"Cresco Labs = {var_1}")
print(f"KFC Ltd (3420) = {var_2}")
print(f"Белуга Групп ПАО (BELU) = {var_3}")

Variance of:
Cresco Labs = 0.16110291188242726
KFC Ltd (3420) = 0.003419614403510552
Белуга Групп ПАО (BELU) = 0.01621767471659818


In [8]:
cov_12 = np.cov(r_1,r_2)
cov_23 = np.cov(r_2,r_3)
cov_13 = np.cov(r_1,r_3)

print("Covariance matrices of:")
print("Cresco Labs and KFC Ltd (3420)")
print(cov_12)
print("KFC Ltd (3420) and Белуга Групп ПАО (BELU)")
print(cov_23)
print("Cresco Labs and Белуга Групп ПАО (BELU)")
print(cov_13)

Covariance matrices of:
Cresco Labs and KFC Ltd (3420)
[[0.16191656 0.01781588]
 [0.01781588 0.00343689]]
KFC Ltd (3420) and Белуга Групп ПАО (BELU)
[[0.00343689 0.00179903]
 [0.00179903 0.01629958]]
Cresco Labs and Белуга Групп ПАО (BELU)
[[0.16191656 0.03256199]
 [0.03256199 0.01629958]]


In [9]:
m = 0.1
print(f"m_* have to be beetween {min(rm_1, rm_2, rm_3)} and {max(rm_1, rm_2, rm_3)}")
print(f"Let it be {m}")

m_* have to be beetween -0.03462631240548707 and 0.3029299630402595
Let it be 0.1


#Постановка задачи

====================================

<Cx,x> -> min

x_1 + x_2 + x_3 = 1

-x_1 < 0 

-x_2 < 0 

-x_3 < 0

μ_1 * x_1 + μ_2 * x_2 + μ_3 * x_3 = m_*

====================================



λ_0 <Cx,x> + λ_1(x_1 + x_2 + x_3 - 1) - λ_2 (x_1) - λ_3 (x_2) - λ_4 (x_3) +  λ_5 (μ_1 * x_1 + μ_2 * x_2 + μ_3 * x_3 - m_*) -> min

-λ_2* x_1 = 0 

-λ_3* x_2 = 0 

-λ_4* x_3 = 0

x_1 + x_2 + x_3 = 1

μ_1 * x_1 + μ_2 * x_2 + μ_3 * x_3 = m_*



In [10]:
# constants
m = 0.1
D_1, D_2, D_3 = 0.16191656, 0.00343689, 0.01629958
m_1, m_2, m_3 = rm_1, rm_2, rm_3

In [11]:
import sympy as sym 
from sympy import *
# parts x_1, x_2, x_3 have to be nonnegative because of problem condition 
# (we can not get loans and reinwest money)
x_1, x_2, x_3 = sym.symbols('x_1 x_2 x_3', float = True, nonnegative=True)

In [12]:
# main_equality that describes optimized function
main_equality = D_1*x_1**2+D_2*x_2**2+D_3*x_3**2 \
+2*cov_12[0][1]*x_1*x_2 + 2*cov_23[0][1]*x_2*x_3+ 2*cov_13[0][1]*x_1*x_3

In [13]:
# definition of profit
profit = m_1*x_1 + m_2*x_2 + m_3*x_3

In [14]:
profit_equality = profit - m

In [15]:
# parts in sum gives us 1
x_equality = x_1 + x_2 + x_3 - 1

In [16]:
lambda_1, lambda_5 = sym.symbols('lambda_1 lambda_5', float = True)
# nonnegative because of nonegative condition of Convex optimization problem
lambda_2, lambda_3, lambda_4 = sym.symbols('lambda_2 lambda_3 lambda_4', float = True, nonnegative=True)

In [17]:
# conditions of complementary non-rigidity
lambda_2_equality = lambda_2 * x_1
lambda_3_equality = lambda_3 * x_2
lambda_4_equality = lambda_4 * x_3

In [18]:
# Lagrangian
lag_func = main_equality + lambda_1 * profit_equality - lambda_2_equality - lambda_3_equality \
- lambda_4_equality + lambda_5 * x_equality
print(lag_func)

lambda_1*(0.302929963040259*x_1 + 0.127119038903125*x_2 - 0.0346263124054871*x_3 - 0.1) - lambda_2*x_1 - lambda_3*x_2 - lambda_4*x_3 + lambda_5*(x_1 + x_2 + x_3 - 1) + 0.16191656*x_1**2 + 0.0356317687118524*x_1*x_2 + 0.0651239742887462*x_1*x_3 + 0.00343689*x_2**2 + 0.00359806892583914*x_2*x_3 + 0.01629958*x_3**2


In [19]:
# Lagrangian derivatives == 0
lag_grad_1 = lag_func.diff(x_1)
print(lag_grad_1)
lag_grad_2 = lag_func.diff(x_2)
print(lag_grad_2)
lag_grad_3 = lag_func.diff(x_3)
print(lag_grad_3)

0.302929963040259*lambda_1 - lambda_2 + lambda_5 + 0.32383312*x_1 + 0.0356317687118524*x_2 + 0.0651239742887462*x_3
0.127119038903125*lambda_1 - lambda_3 + lambda_5 + 0.0356317687118524*x_1 + 0.00687378*x_2 + 0.00359806892583914*x_3
-0.0346263124054871*lambda_1 - lambda_4 + lambda_5 + 0.0651239742887462*x_1 + 0.00359806892583914*x_2 + 0.03259916*x_3


In [20]:
# Solve system
answer = sym.solve((lag_grad_1, lag_grad_2, lag_grad_3, lambda_2_equality,\
                    lambda_3_equality, lambda_4_equality, profit_equality, x_equality),\
                    (x_1, x_2, x_3, lambda_1, lambda_2, lambda_3, lambda_4, lambda_5), dict = True)
answer

[{x_1: 0.0,
  x_2: 0.832334971708822,
  x_3: 0.167665028291178,
  lambda_1: 0.0132058192331648,
  lambda_2: 0.0365737496675651,
  lambda_3: 0.0,
  lambda_4: 0.0,
  lambda_5: -0.00800326885892540}]

In [21]:
print(f"Thus, it turned out, that optimal distribution of shares \
taking into account the specified conditions is following one: \
  \n Cresco Labs: {answer[0][x_1]} \
  \n KFC Ltd(3420){answer[0][x_2]} \
  \n Белуга Групп ПАО (BELU): {answer[0][x_3]}")

Thus, it turned out, that optimal distribution of shares taking into account the specified conditions is following one:   
 Cresco Labs: 0.0   
 KFC Ltd(3420)0.832334971708822   
 Белуга Групп ПАО (BELU): 0.167665028291178
